GET http://localhost:5190/movies

###
GET http://localhost:5190/movies/id/5

###
GET http://localhost:5190/movies/name/john

###
GET http://localhost:5190/movies/genre/1
###
POST http://localhost:5190/movies
Content-Type: application/json

{
    "name": "tukas",
    "genreId": 4,
    "releaseDate": "2024-01-01"
}
###
PUT http://localhost:5190/movies/2
Content-Type: application/json

{
    "name": "John Wick",
    "genreId": 1,
    "releaseDate": "2028-01-01"
}

###
DELETE http://localhost:5190/movies/1